// map.ts
export const icoSets = [
  'hugeicons',
  'iconoir',
  'lucide',
  'mdi',
  'pixelarticons',
]
interface IcoMap {
  [key: string]: {
    [set: string]: string
  }
}

export const map: IcoMap = {
  add: {
    hugeicons: 'i-hugeicons-plus-sign',
    iconoir: 'i-iconoir-plus',
    lucide: 'i-lucide-plus',
    mdi: 'i-mdi-add',
    pixelarticons: 'i-pixelarticons-plus',
  },
  alert: {
    hugeicons: 'i-hugeicons-alert-02',
    iconoir: 'i-iconoir-warning-triangle',
    lucide: 'i-lucide-alert-triangle',
    mdi: 'i-mdi-alert',
    pixelarticons: 'i-pixelarticons-alert',
  },
  'align-bottom': {
    hugeicons: 'i-hugeicons-align-bottom',
    iconoir: 'i-iconoir-comp-align-bottom',
    lucide: 'i-lucide-align-end-horizontal',
    mdi: 'i-mdi-align-vertical-bottom',
    pixelarticons: 'i-pixelarticons-layout-align-bottom',
  },
  'align-center': {
    hugeicons: 'i-hugeicons-align-horizontal-center',
    iconoir: 'i-iconoir-align-horizontal-centers',
    lucide: 'i-lucide-align-center',
    mdi: 'i-mdi-align-horizontal-center',
    pixelarticons: 'i-pixelarticons-layout-distribute-horizontal',
  },
  'align-left': {
    hugeicons: 'i-hugeicons-align-left',
    iconoir: 'i-iconoir-comp-align-left',
    lucide: 'i-lucide-align-start-vertical',
    mdi: 'i-mdi-align-horizontal-left',
    pixelarticons: 'i-pixelarticons-layout-align-left',
  },
  'align-middle': {
    hugeicons: 'i-hugeicons-align-vertical-center',
    iconoir: 'i-iconoir-align-vertical-centers',
    lucide: 'i-lucide-align-vertical-center',
    mdi: 'i-mdi-align-vertical-center',
    pixelarticons: 'i-pixelarticons-layout-distribute-vertical',
  },
  'align-right': {
    hugeicons: 'i-hugeicons-align-right',
    iconoir: 'i-iconoir-comp-align-right',
    lucide: 'i-lucide-align-end-vertical',
    mdi: 'i-mdi-align-horizontal-right',
    pixelarticons: 'i-pixelarticons-layout-align-right',
  },
  'align-text-center': {
    hugeicons: 'i-hugeicons-text-align-center',
    iconoir: 'i-iconoir-align-center',
    lucide: 'i-lucide-align-center',
    mdi: 'i-mdi-format-align-center',
    pixelarticons: 'i-pixelarticons-align-center',
  },
  'align-text-justify': {
    hugeicons: 'i-hugeicons-text-align-justify-center',
    iconoir: 'i-iconoir-align-justify',
    lucide: 'i-lucide-align-justify',
    mdi: 'i-mdi-format-align-justify',
    pixelarticons: 'i-pixelarticons-align-justify',
  },
  'align-text-left': {
    hugeicons: 'i-hugeicons-text-align-left',
    iconoir: 'i-iconoir-align-left',
    lucide: 'i-lucide-align-left',
    mdi: 'i-mdi-format-align-left',
    pixelarticons: 'i-pixelarticons-align-left',
  },
  'align-text-right': {
    hugeicons: 'i-hugeicons-text-align-right',
    iconoir: 'i-iconoir-align-right',
    lucide: 'i-lucide-align-right',
    mdi: 'i-mdi-format-align-right',
    pixelarticons: 'i-pixelarticons-align-right',
  },
  'align-top': {
    hugeicons: 'i-hugeicons-align-top',
    iconoir: 'i-iconoir-comp-align-top',
    lucide: 'i-lucide-align-start-horizontal',
    mdi: 'i-mdi-align-vertical-top',
    pixelarticons: 'i-pixelarticons-layout-align-top',
  },
  archive: {
    hugeicons: 'i-hugeicons-archive',
    iconoir: 'i-iconoir-archive',
    lucide: 'i-lucide-archive',
    mdi: 'i-mdi-archive',
    pixelarticons: 'i-pixelarticons-archive',
  },
  'arrow-down': {
    hugeicons: 'i-hugeicons-arrow-down-02',
    iconoir: 'i-iconoir-arrow-down',
    lucide: 'i-lucide-arrow-down',
    mdi: 'i-mdi-arrow-down',
    pixelarticons: 'i-pixelarticons-arrow-down',
  },
  'arrow-left': {
    hugeicons: 'i-hugeicons-arrow-left-02',
    iconoir: 'i-iconoir-arrow-left',
    lucide: 'i-lucide-arrow-left',
    mdi: 'i-mdi-arrow-left',
    pixelarticons: 'i-pixelarticons-arrow-left',
  },
  'arrow-right': {
    hugeicons: 'i-hugeicons-arrow-right-02',
    iconoir: 'i-iconoir-arrow-right',
    lucide: 'i-lucide-arrow-right',
    mdi: 'i-mdi-arrow-right',
    pixelarticons: 'i-pixelarticons-arrow-right',
  },
  'arrow-up': {
    hugeicons: 'i-hugeicons-arrow-up-02',
    iconoir: 'i-iconoir-arrow-up',
    lucide: 'i-lucide-arrow-up',
    mdi: 'i-mdi-arrow-up',
    pixelarticons: 'i-pixelarticons-arrow-up',
  },
  artboard: {
    hugeicons: 'i-hugeicons-artboard',
    iconoir: 'i-iconoir-frame-alt',
    lucide: 'i-lucide-frame',
    mdi: 'i-mdi-artboard',
    pixelarticons: 'i-pixelarticons-frame',
  },
  at: {
    hugeicons: 'i-hugeicons-at',
    iconoir: 'i-iconoir-at-sign',
    lucide: 'i-lucide-at-sign',
    mdi: 'i-mdi-at',
    pixelarticons: 'i-pixelarticons-at',
  },
  attach: {
    hugeicons: 'i-hugeicons-attachment',
    iconoir: 'i-iconoir-attachment',
    lucide: 'i-lucide-link-2',
    mdi: 'i-mdi-attachment',
    pixelarticons: 'i-pixelarticons-attachment',
  },
  battery: {
    hugeicons: 'i-hugeicons-battery-empty',
    iconoir: 'i-iconoir-battery-empty',
    lucide: 'i-lucide-battery',
    mdi: 'i-mdi-battery',
    pixelarticons: 'i-pixelarticons-battery',
  },
  'battery-charging': {
    hugeicons: 'i-hugeicons-battery-charging-01',
    iconoir: 'i-iconoir-battery-charging',
    lucide: 'i-lucide-battery-charging',
    mdi: 'i-mdi-battery-charging',
    pixelarticons: 'i-pixelarticons-battery-charging',
  },
  'battery-full': {
    hugeicons: 'i-hugeicons-battery-full',
    iconoir: 'i-iconoir-battery-full',
    lucide: 'i-lucide-battery-full',
    mdi: 'i-mdi-battery-full',
    pixelarticons: 'i-pixelarticons-battery-full',
  },
  bed: {
    hugeicons: 'i-hugeicons-bed',
    iconoir: 'i-iconoir-bed',
    lucide: 'i-lucide-bed',
    mdi: 'i-mdi-bed',
    pixelarticons: 'i-pixelarticons-bed',
  },
  bluetooth: {
    hugeicons: 'i-hugeicons-bluetooth',
    iconoir: 'i-iconoir-bluetooth',
    lucide: 'i-lucide-bluetooth',
    mdi: 'i-mdi-bluetooth',
    pixelarticons: 'i-pixelarticons-bluetooth',
  },
  book: {
    hugeicons: 'i-hugeicons-book-02',
    iconoir: 'i-iconoir-book',
    lucide: 'i-lucide-book',
    mdi: 'i-mdi-book',
    pixelarticons: 'i-pixelarticons-book',
  },
  'book-open': {
    hugeicons: 'i-hugeicons-book-open-01',
    iconoir: 'i-iconoir-open-book',
    lucide: 'i-lucide-book-open',
    mdi: 'i-mdi-book-open',
    pixelarticons: 'i-pixelarticons-book-open',
  },
  bookmark: {
    hugeicons: 'i-hugeicons-bookmark-01',
    iconoir: 'i-iconoir-bookmark',
    lucide: 'i-lucide-bookmark',
    mdi: 'i-mdi-bookmark',
    pixelarticons: 'i-pixelarticons-bookmark',
  },
  briefcase: {
    hugeicons: 'i-hugeicons-briefcase-02',
    iconoir: 'i-iconoir-suitcase',
    lucide: 'i-lucide-briefcase',
    mdi: 'i-mdi-briefcase',
    pixelarticons: 'i-pixelarticons-briefcase',
  },
  building: {
    hugeicons: 'i-hugeicons-building-02',
    iconoir: 'i-iconoir-building',
    lucide: 'i-lucide-building',
    mdi: 'i-mdi-building',
    pixelarticons: 'i-pixelarticons-building',
  },
  bus: {
    hugeicons: 'i-hugeicons-bus-01',
    iconoir: 'i-iconoir-bus',
    lucide: 'i-lucide-bus',
    mdi: 'i-mdi-bus',
    pixelarticons: 'i-pixelarticons-bus',
  },
  cake: {
    hugeicons: 'i-hugeicons-birthday-cake',
    iconoir: 'i-iconoir-birthday-cake',
    lucide: 'i-lucide-cake',
    mdi: 'i-mdi-cake',
    pixelarticons: 'i-pixelarticons-cake',
  },
  calculator: {
    hugeicons: 'i-hugeicons-calculator-01',
    iconoir: 'i-iconoir-calculator',
    lucide: 'i-lucide-calculator',
    mdi: 'i-mdi-calculator',
    pixelarticons: 'i-pixelarticons-calculator',
  },
  calendar: {
    hugeicons: 'i-hugeicons-calendar-03',
    iconoir: 'i-iconoir-calendar',
    lucide: 'i-lucide-calendar',
    mdi: 'i-mdi-calendar',
    pixelarticons: 'i-pixelarticons-calendar',
  },
  'calendar-add': {
    hugeicons: 'i-hugeicons-calendar-01',
    iconoir: 'i-iconoir-calendar-plus',
    lucide: 'i-lucide-calendar-plus',
    mdi: 'i-mdi-calendar-add',
    pixelarticons: 'i-pixelarticons-calendar-plus',
  },
  camera: {
    hugeicons: 'i-hugeicons-camera-01',
    iconoir: 'i-iconoir-camera',
    lucide: 'i-lucide-camera',
    mdi: 'i-mdi-camera',
    pixelarticons: 'i-pixelarticons-camera',
  },
  car: {
    hugeicons: 'i-hugeicons-car-01',
    iconoir: 'i-iconoir-car',
    lucide: 'i-lucide-car',
    mdi: 'i-mdi-car',
    pixelarticons: 'i-pixelarticons-car',
  },
  cast: {
    hugeicons: 'i-hugeicons-mirroring-screen',
    iconoir: 'i-iconoir-chromecast',
    lucide: 'i-lucide-cast',
    mdi: 'i-mdi-cast',
    pixelarticons: 'i-pixelarticons-cast',
  },
  chat: {
    hugeicons: 'i-hugeicons-bubble-chat',
    iconoir: 'i-iconoir-message',
    lucide: 'i-lucide-message-circle',
    mdi: 'i-mdi-chat',
    pixelarticons: 'i-pixelarticons-chat',
  },
  check: {
    hugeicons: 'i-hugeicons-tick-01',
    iconoir: 'i-iconoir-check',
    lucide: 'i-lucide-check',
    mdi: 'i-mdi-check',
    pixelarticons: 'i-pixelarticons-check',
  },
  'check-double': {
    hugeicons: 'i-hugeicons-tick-double-01',
    iconoir: 'i-iconoir-double-check',
    lucide: 'i-lucide-check-check',
    mdi: 'i-mdi-check-all',
    pixelarticons: 'i-pixelarticons-check-double',
  },
  'chevron-down': {
    hugeicons: 'i-hugeicons-arrow-down-01',
    iconoir: 'i-iconoir-nav-arrow-down',
    lucide: 'i-lucide-chevron-down',
    mdi: 'i-mdi-chevron-down',
    pixelarticons: 'i-pixelarticons-chevron-down',
  },
  'chevron-left': {
    hugeicons: 'i-hugeicons-arrow-left-01',
    iconoir: 'i-iconoir-nav-arrow-left',
    lucide: 'i-lucide-chevron-left',
    mdi: 'i-mdi-chevron-left',
    pixelarticons: 'i-pixelarticons-chevron-left',
  },
  'chevron-right': {
    hugeicons: 'i-hugeicons-arrow-right-01',
    iconoir: 'i-iconoir-nav-arrow-right',
    lucide: 'i-lucide-chevron-right',
    mdi: 'i-mdi-chevron-right',
    pixelarticons: 'i-pixelarticons-chevron-right',
  },
  'chevron-up': {
    hugeicons: 'i-hugeicons-arrow-up-01',
    iconoir: 'i-iconoir-nav-arrow-up',
    lucide: 'i-lucide-chevron-up',
    mdi: 'i-mdi-chevron-up',
    pixelarticons: 'i-pixelarticons-chevron-up',
  },
  circle: {
    hugeicons: 'i-hugeicons-circle',
    iconoir: 'i-iconoir-circle',
    lucide: 'i-lucide-circle',
    mdi: 'i-mdi-circle',
    pixelarticons: 'i-pixelarticons-circle',
  },
  clock: {
    hugeicons: 'i-hugeicons-clock-01',
    iconoir: 'i-iconoir-clock',
    lucide: 'i-lucide-clock',
    mdi: 'i-mdi-clock',
    pixelarticons: 'i-pixelarticons-clock',
  },
  close: {
    hugeicons: 'i-hugeicons-cancel-01',
    iconoir: 'i-iconoir-xmark',
    lucide: 'i-lucide-x',
    mdi: 'i-mdi-close',
    pixelarticons: 'i-pixelarticons-close',
  },
  cloud: {
    hugeicons: 'i-hugeicons-cloud',
    iconoir: 'i-iconoir-cloud',
    lucide: 'i-lucide-cloud',
    mdi: 'i-mdi-cloud',
    pixelarticons: 'i-pixelarticons-cloud',
  },
  'cloud-download': {
    hugeicons: 'i-hugeicons-cloud-download',
    iconoir: 'i-iconoir-cloud-download',
    lucide: 'i-lucide-cloud-download',
    mdi: 'i-mdi-cloud-download',
    pixelarticons: 'i-pixelarticons-cloud-download',
  },
  code: {
    hugeicons: 'i-hugeicons-code',
    iconoir: 'i-iconoir-code',
    lucide: 'i-lucide-code',
    mdi: 'i-mdi-code',
    pixelarticons: 'i-pixelarticons-code',
  },
  comment: {
    hugeicons: 'i-hugeicons-comment-01',
    iconoir: 'i-iconoir-message-text',
    lucide: 'i-lucide-message-square-text',
    mdi: 'i-mdi-comment',
    pixelarticons: 'i-pixelarticons-comment',
  },
  copy: {
    hugeicons: 'i-hugeicons-copy-01',
    iconoir: 'i-iconoir-copy',
    lucide: 'i-lucide-copy',
    mdi: 'i-mdi-content-copy',
    pixelarticons: 'i-pixelarticons-copy',
  },
  'credit-card': {
    hugeicons: 'i-hugeicons-credit-card',
    iconoir: 'i-iconoir-credit-card',
    lucide: 'i-lucide-credit-card',
    mdi: 'i-mdi-credit-card',
    pixelarticons: 'i-pixelarticons-credit-card',
  },
  crop: {
    hugeicons: 'i-hugeicons-crop',
    iconoir: 'i-iconoir-crop',
    lucide: 'i-lucide-crop',
    mdi: 'i-mdi-crop',
    pixelarticons: 'i-pixelarticons-crop',
  },
  download: {
    hugeicons: 'i-hugeicons-download-05',
    iconoir: 'i-iconoir-download',
    lucide: 'i-lucide-download',
    mdi: 'i-mdi-download',
    pixelarticons: 'i-pixelarticons-download',
  },
  duplicate: {
    hugeicons: 'i-hugeicons-copy-01',
    iconoir: 'i-iconoir-copy',
    lucide: 'i-lucide-copy',
    mdi: 'i-mdi-content-duplicate',
    pixelarticons: 'i-pixelarticons-duplicate',
  },
  edit: {
    hugeicons: 'i-hugeicons-edit-02',
    iconoir: 'i-iconoir-edit',
    lucide: 'i-lucide-edit',
    mdi: 'i-mdi-edit',
    pixelarticons: 'i-pixelarticons-edit',
  },
  heart: {
    hugeicons: 'i-hugeicons-favourite',
    iconoir: 'i-iconoir-heart',
    lucide: 'i-lucide-heart',
    mdi: 'i-mdi-heart',
    pixelarticons: 'i-pixelarticons-heart',
  },
  home: {
    hugeicons: 'i-hugeicons-home-03',
    iconoir: 'i-iconoir-home',
    lucide: 'i-lucide-home',
    mdi: 'i-mdi-home',
    pixelarticons: 'i-pixelarticons-home',
  },
  lightbulb: {
    hugeicons: 'i-hugeicons-bulb',
    iconoir: 'i-iconoir-light-bulb',
    lucide: 'i-lucide-lightbulb',
    mdi: 'i-mdi-lightbulb',
    pixelarticons: 'i-pixelarticons-lightbulb',
  },
  link: {
    hugeicons: 'i-hugeicons-link-04',
    iconoir: 'i-iconoir-link',
    lucide: 'i-lucide-link',
    mdi: 'i-mdi-link',
    pixelarticons: 'i-pixelarticons-link',
  },
  list: {
    hugeicons: 'i-hugeicons-left-to-right-list-bullet',
    iconoir: 'i-iconoir-list',
    lucide: 'i-lucide-list',
    mdi: 'i-mdi-format-list-bulleted',
    pixelarticons: 'i-pixelarticons-list',
  },
  'sign-dollar': {
    hugeicons: 'i-hugeicons-dollar-01',
    iconoir: 'i-iconoir-dollar',
    lucide: 'i-lucide-dollar-sign',
    mdi: 'i-mdi-dollar',
    pixelarticons: 'i-pixelarticons-dollar',
  },
  'sign-euro': {
    hugeicons: 'i-hugeicons-euro',
    iconoir: 'i-iconoir-euro',
    lucide: 'i-lucide-euro',
    mdi: 'i-mdi-euro',
    pixelarticons: 'i-pixelarticons-euro',
  },
}

export default map
